	[org 0x7c00]
	[bits 16]

boot:
	xor ax, ax
	mov ss, ax
	mov ds, ax
	mov es, ax
	mov gs, ax
	mov fs, ax
	mov sp, 0x7bff

	mov byte[DRIVE_NUMBER], dl

	mov al, 0x02
	mov ch, 0x00
	mov cl, 0x02
	mov dh, 0x00
	mov bx, 0x7e00
	call disk_16b

	mov ax, 1024
	mov bx, 768
	mov cl, 32
	call video_setup_16b
	
	jmp $

	%include "16b/video_setup_16b.asm"
	%include "16b/print_textm_hex_16b.asm"
	%include "16b/disk_16b.asm"

DRIVE_NUMBER:			db 0
	
	times 510 - ($ - $$) db 0
	dw 0xaa55


	
VESA_RETURN:	
VESARETURN_SIGNATURE:			db 'VBE2'
VESARETURN_VERSION:			dw 0
VESARETURN_PTR_OEMNAME:			dd 0
VESARETURN_FUNCTIONS:			dd 0
VESARETURN_MODES_OFFSET:		dw 0
VESARETURN_MODES_SEGMENT:		dw 0
VESARETURN_NUM_64KBLOCKS:		dw 0
VESARETURN_OEMSOFTWAREREVISION:		dw 0
VESARETURN_PTR_OEMVENDORNAME:		dd 0
VESARETURN_PTR_OEMPRODUCTNAME:		dd 0
VESARETURN_PTR_OEMPRODUCTREVISION:	dd 0
VESARETURN_RESERVED:			times 222 db 0
VESARETURN_OEMDATA:			times 256 db 0


	
VESA_MODE_RETURN:	
VESA_MODE_RETURN_ATRIBUTES:		dw 0
VESA_MODE_RETURN_FIRSTWINDOW:		db 0
VESA_MODE_RETURN_SECWINDOW:		db 0
VESA_MODE_RETURN_GRANULARITY:		dw 0  	
VESA_MODE_RETURN_WINDOWSIZE:		dw 0
VESA_MODE_RETURN_FIRSTWINDOWSEGMENT:	dw 0
VESA_MODE_RETURN_SECWINDOWSEGMENT:	dw 0
VESA_MODE_RETURN_PTR_WINDOWFUNC:	dd 0
VESA_MODE_RETURN_BYTESPERSCANLINE:	dw 0
VESA_MODE_RETURN_WIDTH:			dw 0
VESA_MODE_RETURN_HEIGHT:		dw 0
VESA_MODE_RETURN_CHARWIDTH:		db 0
VESA_MODE_RETURN_CHARHEIGHT:		db 0
VESA_MODE_RETURN_PLANESNUM:		db 0
VESA_MODE_RETURN_BPP:			db 0
VESA_MODE_RETURN_BANKSNUM:		db 0
VESA_MODE_RETURN_MEMMODEL:		db 0
VESA_MODE_RETURN_BANKSIZE:		db 0
VESA_MODE_RETURN_IMAGEPAGESCOUNT:	db 0
VESA_MODE_RETURN_RESERVED:		db 0
	
VESA_MODE_RETURN_REDMASKSIZE:		db 0
VESA_MODE_RETURN_REDFIELDPOSITION:	db 0
VESA_MODE_RETURN_GREENMASKSIZE:		db 0
VESA_MODE_RETURN_GREENFIELDPOSITION:	db 0
VESA_MODE_RETURN_BLUEMASKSIZE:		db 0
VESA_MODE_RETURN_BLUEFIELDPOSITION:	db 0
VESA_MODE_RETURN_RESERVEDMASKSIZE:	db 0
VESA_MODE_RETURN_RESERVEDMASKPOSITION:	db 0
VESA_MODE_RETURN_DIRECTCOLORMODEINFO:	db 0

VESA_MODE_RETURN_LFBADDRESS:		dd 0
VESA_MODE_RETURN_OUTMEMOFFSET:		dd 0
VESA_MODE_RETURN_OUTMEMSIZE:		dw 0
VESA_MODE_RETURN_RESERVED1:		times 206 db 0



VESASCREEN_WIDTH:		dw 0
VESASCREEN_HEIGHT:		dw 0
VESASCREEN_FRAMEBUFFER:		dd 0
VESASCREEN_BYTESPERSCANLINE:	dw 0

times (256 - 10) db 0
